# Generated by go2rpm 1
%bcond_without check

# https://github.com/blevesearch/snowballstem
%global goipath         github.com/blevesearch/snowballstem
%global commit          26b06a2c243d4f8ca5db3486f94409dd5b2a7467

%gometa

%global common_description %{expand:
Go stemmers generated by the Snowball project.}

%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go stemmers generated by the Snowball project

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Jan 26 03:07:34 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 0-0.1.20200126git26b06a2
- Initial package
